baseURL = 'https://g4mless.github.io/'
languageCode = 'id-id'
title = 'g4mless-blog'
theme = 'github-style'
pygmentsCodeFences = true
pygmentsUseClasses = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  author = "g4mless"
  description = "Dev malas, tech nerd, casual gamer."
  github = "g4mless"
  facebook = "g4mless"
  twitter = "g4mless"
  email = "g4mless@proton.me"
  url = "https://g4mless.github.io"
  keywords = "blog, docs"
  rss = true
  lastmod = true
  favicon = "/images/github-mark.png"
  avatar = "/images/avatar.png"
  headerIcon = "/images/github-mark-white.png"
  location = "Indonesia"
  enableGitalk = false
  enableSearch = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'